FROM php:7.1-apache

RUN docker-php-ext-install mysqli pdo_mysql

# RUN echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf
# RUN service apache2 reload

# enable service.
# RUN systemctl enable httpd

# exec.
# CMD ["/sbin/init"]
